#!/bin/bash

# Saves the current revision number

# NewRev=`svn info | grep "Revision" | awk -F: '{ print $2 }'`
#NewRev=`svnversion | awk -F: '{ print $2 }' | awk -F'M' '{ print $1 }'`

if ( `test ! -d ${NUSIM}/.svn` ) && ( `test ! -d ${NUSIM}/config/revision.txt` ); then
  echo "Error: Neither a svn directory nor a default revision.txt file found."
  echo "       The revision number in the output files will be wrong."
  exit 0;
fi

echo "Checking NuSIM svn revision... This might take a moment..."
NewRev=`svnversion`
NewRev=$(echo $NewRev|sed 's/M/ /g'); 
if [[ $NewRev == *:* ]]; then 
  NewRev=`echo $NewRev | awk -F: '{ print $2 }'`; 
fi;

if (`test ! -f ${NUSIM}/config/revision.txt`); then
  echo "Create revision file: $NewRev"
  echo $NewRev >>  ${NUSIM}/config/revision.txt
else 
  OldRev=`cat ${NUSIM}/config/revision.txt`
  if ([ $NewRev -ne $OldRev ]); then
    rm -f ${NUSIM}/config/revision.txt 
    echo "Updating revision file to: $NewRev"
    echo $NewRev >>  ${NUSIM}/config/revision.txt  
  else 
    echo "Revision file up to date: $OldRev"
  fi 
fi

exit 0;

