#!/bin/bash

# Saves the current revision number

# NewRev=`svn info | grep "Revision" | awk -F: '{ print $2 }'`
#NewRev=`svnversion | awk -F: '{ print $2 }' | awk -F'M' '{ print $1 }'`
NewRev=`svnversion`
NewRev=$(echo $NewRev|sed 's/M/ /g'); 
if [[ $NewRev == *:* ]]; then 
  NewRev=`echo $NewRev | awk -F: '{ print $2 }'`; 
fi;

if (`test ! -f ${NUSIM}/config/revision.txt`); then
  echo "Create revision file: $NewRev"
  echo $NewRev >>  ${NUSIM}/config/revision.txt
  #echo " " >>  ${NUSIM}/config/revision.txt  
else 
  OldRev=`cat ${NUSIM}/config/revision.txt`
  echo "$NewRev ->  $OldRev"
  if ([ $NewRev -gt $OldRev ]); then
    rm -f ${NUSIM}/config/revision.txt 
    echo "Updating revision file to: $NewRev"
    echo $NewRev >>  ${NUSIM}/config/revision.txt  
    #echo " " >>  ${NUSIM}/config/revision.txt  
  else 
    echo "Revision file up to date: $OldRev"
  fi 
fi

exit 0;

